### PR TITLE
add Webknossos samples

### PR DESCRIPTION
**Pull request by normanrz**
Adds public datasets from the [WEBKNOSSOS publication gallery](https://webknossos.org/publications). In total 326TB.
I am using the columns `url,source,bytes`. Feel free to change.

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @normanrz!

**Comment by will-moore** [comment]
@normanrz Just checking on these samples, it seems strange to me that the 9 pyramid resolutions at https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M1/color are all the same shape? 

In fact, that seems to be the case for all the samples I've checked so far.

**Comment by will-moore** [comment]
Only the smaller images are viewable in vizarr, but they don't appear to be rendering correctly, e.g. https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/Demo_Organization/GK18_PLOS_Mouse1/color

(don't know if that is vizarr issue or not)?

Screenshot 2024-09-30 at 12 27 44

In the samples viewer, the thumbnail for that image appears like:

Screenshot 2024-09-30 at 12 29 53

**Comment by MichaelBuessemeyer** [comment]
> @normanrz Just checking on these samples, it seems strange to me that the 9 pyramid resolutions at https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M1/color are all the same shape?

Hi @will-moore,
Thanks for identifying this issue. It should (hopefully) be fixed now. Could you please give this another check?

> Only the smaller images are viewable in vizarr, but they don't appear to be rendering correctly, e.g. https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/Demo_Organization/GK18_PLOS_Mouse1/color

About what's going on here, we are unsure. It looks like an axis mixup or something like that, but we were unable to identify further mistakes within the zarr v3 streaming of WEBKNOSSOS.

**Comment by will-moore** [comment]
Thanks @MichaelBuessemeyer - it looks like a lot of the samples are fixed.
But there's a bunch of others that still have this issue.

This hopefully gives a good overview: https://ome.github.io/ome2024-ngff-challenge/?csv=https://raw.githubusercontent.com/will-moore/ome2024-ngff-challenge/samples_viewer/samples/webknossos_samples.csv

Here, I'm not attempting to load thumbnails where the smallest resolution is larger than 512 x 512 in X and Y (last 2 dimensions), so, most of the rows with no thumbnails indicate Zarrs where the pyramid isn't downsampled.

NB: I also noticed that your dimension order is `CXYZ`:
```
"dimension_names": ["c", "x", "y", "z"]
```
so your last 2 dimensions are Y and Z, whereas the current expectation with OME-Zarr is that the order is `CZYX`. This probably won't break most tools since you have 3D chunks, but might get unexpected results in some cases.

**Comment by normanrz** [comment]
I just upgraded our second server. Now all samples should show up. 



> NB: I also noticed that your dimension order is `CXYZ`:
> 
> ```
> "dimension_names": ["c", "x", "y", "z"]
> ```

I know. Since we are using F order with only a single channel it is binary equivalent to czyx in C order. Anyways, RFC-3 should help clear this up.

**Comment by will-moore** [comment]
Thanks, that's most of them working now...
Just a couple of issues: for these images, the last resolution level is bigger than the previous level and other levels are also not ordered by size:
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://demo.data2-brain.esc.rzg.mpg.de/data/zarr3_experimental/MPI_Brain_Research/HS_st218_MT3/color
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://demo.data2-brain.esc.rzg.mpg.de/data/zarr3_experimental/MPI_Brain_Research/HS_st218_MT2_new/color
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://demo.data2-brain.esc.rzg.mpg.de/data/zarr3_experimental/MPI_Brain_Research/HS_st218_MT4/color
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://demo.data2-brain.esc.rzg.mpg.de/data/zarr3_experimental/MPI_Brain_Research/HS_st218_MT1/color
 
There are a couple of others that are perfectly valid, but I'm just not loading thumbnail because the smallest resolution is a little too large (which is fine):
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/Demo_Organization/e1088_large/color
 - https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://demo.data2-brain.esc.rzg.mpg.de/data/zarr3_experimental/MPI_Brain_Research/2012-06-26_C80_11/color

**Comment by will-moore** [comment]
Since Jason was asking about thumbnails for webknossos images at https://ome.github.io/ome2024-ngff-challenge/?csv=https://raw.githubusercontent.com/will-moore/ome2024-ngff-challenge/samples_viewer/samples/webknossos_samples.csv, I looked into this a bit more and I'm pretty sure this is due to the dimension order issue above:

E.g. https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M2/color

If I try to view individual resolutions in vizarr (instead of viewing the whole multi-dimensional pyramid at once) then I see that it looks like the chunks are not orientated in the right way:
Lowest resolution:
https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M2/color/256-256-32/&viewState={%22zoom%22:1.7052122982361007,%22target%22:[42.27329555040177,63.1724454344384]}

Screenshot 2024-10-14 at 09 51 24

Next lowest: https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M2/color/128-128-16/&viewState={%22zoom%22:0.8564207383980663,%22target%22:[104.518410580058,115.08842654474404]}

Screenshot 2024-10-14 at 09 51 43

And next: https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M2/color/64-64-8/&viewState={%22zoom%22:0.555258473610333,%22target%22:[152.94428097985218,234.9591302232228]}

Screenshot 2024-10-14 at 09 53 30

I don't know if there's a way to work around this, either manually with the way I'm creating thumbnails using zarrita, or in vizarr itself? cc @manzt

**Comment by MichaelBuessemeyer** [comment]
Thank you for your report about the incorrect resolution level ordering @will-moore.

It should now be fixed and the fix should also be deployed on the relevant hosted WEBKNOSSOS instances.

**Comment by will-moore** [comment]
Thanks @MichaelBuessemeyer but at least with the tests above using vizarr, I'm not seeing any change yet: e.g. https://hms-dbmi.github.io/vizarr/?source=https://data-humerus.webknossos.org/data/zarr3_experimental/b2275d664e4c2a96/HuaLab-CBA_Ca-mouse-unexposed-M2/color/256-256-32/ looks as it does above.

And I'm seeing similar effects with the other image thumbnails at https://will-moore.github.io/ome2024-ngff-challenge/?csv=https://raw.githubusercontent.com/will-moore/ome2024-ngff-challenge/hierarchy_browser/samples/webknossos_samples.csv

Maybe these are just caching artifacts?

**Pull request merged**
